ALTER TABLE certificate_used
    ENGINE = innodb;
ALTER TABLE statistic
    ENGINE = innodb;
ALTER TABLE sdt_files
    ENGINE = innodb;
ALTER TABLE sdt_api_user_data
    ENGINE = innodb;
ALTER TABLE sdt_act
    ENGINE = innodb;
ALTER TABLE certificate_reserved
    ENGINE = innodb;
ALTER TABLE document_numbers_used
    ENGINE = innodb;
ALTER TABLE sdt_act_status
    ENGINE = innodb;
ALTER TABLE sdt_act_test
    ENGINE = innodb;
ALTER TABLE act_summary_table
    ENGINE = innodb;
ALTER TABLE print_numbers
    ENGINE = innodb;
ALTER TABLE certificate_duplicate
    ENGINE = innodb;
ALTER TABLE dubl_act
    ENGINE = innodb;
ALTER TABLE dubl_act_man
    ENGINE = innodb;
ALTER TABLE sdt_university
    ENGINE = innodb;
ALTER TABLE sdt_university_dogovor
    ENGINE = innodb;
ALTER TABLE sdt_university_signing
    ENGINE = innodb;
ALTER TABLE sdt_signing
    ENGINE = innodb;
ALTER TABLE certificate_invalid
    ENGINE = innodb;
ALTER TABLE act_metadata
    ENGINE = innodb;
ALTER TABLE country
    ENGINE = innodb;
ALTER TABLE sdt_test_levels
    ENGINE = innodb;
ALTER TABLE tb_users
    ENGINE = innodb;