<?php
require_once 'Model.php';
require_once 'Session.php';
require_once 'university.php';
require_once 'university_dogovor.php';
require_once 'test_levels.php';
require_once 'act.php';
require_once 'act_test.php';
require_once 'act_people.php';
require_once 'act_signing.php';
require_once 'country.php';
require_once 'otchet.php';
require_once 'otchet/country.php';
require_once 'files.php';
require_once __DIR__ . '/Act/ActSummaryTable.php';
require_once 'head_center.php';
require_once 'head_org.php';
require_once 'head_center_text.php';
require_once 'user.php';
require_once 'user_type.php';
require_once 'test_levels_changed_price.php';
require_once 'test\sub_test.php';
require_once 'test\sub_test_result.php';
require_once 'test_level_type.php';
require_once __DIR__ . '/Certificate/certificate_reserved.php';
require_once __DIR__ . '/Certificate/document_numbers.php';
require_once __DIR__ . '/Certificate/certificate_used.php';
require_once __DIR__ . '/Certificate/certificate_invalid.php';
require_once __DIR__ . '/Certificate/certificate_duplicate.php';
require_once __DIR__ . '/Certificate/people_additional_exam.php';
require_once 'special_prices.php';
require_once 'special_prices_university.php';
require_once 'act_metadata.php';
require_once 'Api/ApiUserData.php';
require_once 'Message/Thread.php';
require_once 'Message/ThreadParticipant.php';
require_once 'Message/Message.php';
require_once 'Message/MessageMeta.php';
require_once 'regions.php';
require_once 'Dubl\DublAct.php';
require_once 'Dubl\DublActMan.php';
require_once 'print_numbers.php';
require_once 'test\subtest_group.php';
require_once 'test\subtest_meta.php';
require_once 'test\calculation.php';
require_once 'blank_types.php';
require_once 'Logs\ActionRunLog.php';
require_once 'annul_certs.php';
require_once __DIR__ . '/Center/center_signing.php';
require_once 're_exam_info.php';
require_once 'html_act_files.php';
//require_once 'Logs\SqlErrorLog.php';


